export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"

export const GET_AEONS = 'GET_AEONS';
export const AEONS_LOADING = 'AEONS_LOADING';

export const GET_CARREFOURS = 'GET_CARREFOURS';
export const CARREFOURS_LOADING = 'CARREFOURS_LOADING';

export const GET_FARMERS = 'GET_FARMERS';
export const FARMERS_LOADING = 'FARMERS_LOADING';

export const GET_FOODHALLS = 'GET_FOODHALLS';
export const FOODHALLS_LOADING = 'FOODHALLS_LOADING';

export const GET_GRANDS = 'GET_GRANDS';
export const GRANDS_LOADING = 'GRANDS_LOADING';
